### ISSUE TITLE
case sensitivity issue under linux

### ISSUE THREAD

**Issue by angst7** [cnoviello/CubeMXImporter#1]
There is a missing .lower() on self.HAL_TYPE in the deleteOriginalEclipseProjectFiles method, line 134. This causes a file or directory not found error under linux as stm32F4xx and stm32f4xx get used interchangeably.  I'm attaching a simple patch that worked for me. 

[patch.txt](https://github.com/cnoviello/CubeMXImporter/files/39434/patch.txt)

**Comment by cnoviello** [comment]
Yes, you are right. I'm going to add it to the code. Thanks to submitting the patch ;-)
