### ISSUE TITLE
wrong regexp for HAL_MCU_TYPE

### ISSUE THREAD

**Issue by Ivan-SB** [cnoviello/CubeMXImporter#2]
self.HAL_TYPE = re.split("([F,L]{1}[0-9]{1})", self.HAL_MCU_TYPE)[1]
the , in [F,L] is plain wrong, check with STM32,103RBTx
the {1} is redundant and there is no need for the split as well.

Try with something like re.search("([FL][0-9])", self.MCU).group(1))

**Comment by cnoviello** [comment]
I've to admit that I'm not good with regular expressions. It's not my forte. 

I'll check and let you know.

**Comment by Ivan-SB** [comment]
To make it easier:
in [] you just list the characters you want to include so [FL] is enough, adding the , means that ',' is accepted, that's not what you want.
By default [listofchar] means one in the set, no need to add {N} if N=1.

There are a lot of regex dialects and you can do pretty fancy stuff with regex, I'm far from being a regex black belt either ;)

BTW I stumbled on your project because I'm writing something similar with the intent to be able to change the underlying HAL library and be able to "move" around the eclipse project.
Considering eclipse doesn't support relative links to external resource nicely (or maybe I'm missing somethng), it's a bit hakish but it will give me more freedom and that's the main reason I picked up GNU ARM plugin inspite of using ST eclipse based dev env. I've been burned before by atmel AVR32 dev env switching to Visual Studio ;)

I think I'll have a working version on github in a couple of days hopefully and it is going to be GPL.
Possibly I'll extract a library to inject external libraries in eclipse C projects and still be able to move them around on system without being stuck to an absolute path.

thanks for your blog posts and this inspirational project

**Comment by cnoviello** [comment]
I can confirm that it works. Thanks.
